spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/live_lyrics?serverTimezone=UTC
    username: root
    password: 19980518
  data:
    mongodb:
      uri: mongodb+srv://chunkie0518:Gsc-980518@live-lyrics-mongodb.zmz6vzs.mongodb.net/
      database: live_lyrics
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1