spring:
  datasource:
    url: jdbc:mysql://awseb-e-sfyqpij8ah-stack-awsebrdsdatabase-afhwqp59szm2.c3c8ig6y4i0d.ap-southeast-2.rds.amazonaws.com:3306/ebdb
    username: chunkie0518
    password: Gsc-980518
  data:
    mongodb:
      uri: mongodb+srv://chunkie0518:Gsc-980518@live-lyrics-mongodb.zmz6vzs.mongodb.net/
      database: live_lyrics
  redis:
    host: redis-13003.c296.ap-southeast-2-1.ec2.cloud.redislabs.com
    port: 13003
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1
    username: default
    password: Gsc-980518

square:
  environment: production
  accessToken: EAAAlxDYB-mK3Xfonw14LqY5jmWBKOmBzGRr8pMEh1bsSu98Q0tA1xaN9MKN2MmH