name: Deployment to Elastic Beanstalk
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package -DskipTests -Pprod --file pom.xml
      - name: Create ZIP artifact
        run: zip -r artifact.zip .platform target/live_lyrics_server-0.0.1-SNAPSHOT.jar
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.zip
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download ZIP
        uses: actions/download-artifact@v4
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: busklive-spring-boot
          environment_name: Busklive-spring-boot-env
          version_label: ${{github.SHA}}
          region: ap-southeast-2
          deployment_package: live_lyrics_server-0.0.1-SNAPSHOT.jar